language: r
cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

r:
  - oldrel
  - release
  - devel

sudo: false

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'library(lintr); lint_package()'
